In [21]:
import pandas as pd
csvFile = 'Real_Estate_Sales.csv'
reHandle = pd.read_csv(csvFile)
print(reHandle.head(10))
num_data_points = reHandle.shape[0]
column_names = reHandle.columns
statistical_summary = reHandle.describe()
print(f"\n\n")
print(f"The number of data points are {num_data_points} \n\n")
print(f"Here are the column names: \n\n{column_names}\n\n")
print(f"Here is a statistical summary: \n\n {statistical_summary}\n\n")


df = pd.DataFrame(reHandle)
print("The years listed in the dataset: ")
print(df['List Year'])
city1 = 'Danbury'
city2 = 'Bristol'
city1_data = df.loc[df['Town'] == city1]
city2_data = df.loc[df['Town'] == city2]
mean_city1 = city1_data['Sale Amount'].mean()
mean_city2 = city2_data['Sale Amount'].mean()
min_city1 = city1_data['Sale Amount'].min()
minn_city2 = city2_data['Sale Amount'].min()
max_city1 = city1_data['Sale Amount'].max()
max_city2 = city2_data['Sale Amount'].max()
if mean_city1 > mean_city2:
    print(f"On average, single-family homes are more expensive in {city1}.")
elif mean_city1 < mean_city2:
    print(f"On average, single-family homes are more expensive in {city2}.")
else:
    print("The average sale amounts for single-family homes are the same in both cities.")

   Serial Number  List Year Date Recorded          Town           Address  \
0        2020177       2020     4/14/2021       Ansonia     323 BEAVER ST
1        2020225       2020     5/26/2021       Ansonia    152 JACKSON ST
2        2020348       2020     9/13/2021       Ansonia   230 WAKELEE AVE
3        2020090       2020    12/14/2020       Ansonia       57 PLATT ST
4         200500       2020      9/7/2021          Avon      245 NEW ROAD
5         200121       2020    12/15/2020          Avon      63 NORTHGATE
6          20058       2020      6/1/2021   Barkhamsted  46 RATLUM MTN RD
7         200046       2020     1/25/2021  Beacon Falls     34 LASKY ROAD
8         200016       2020    11/13/2020  Beacon Falls      9 AVON COURT
9        2020360       2020     8/10/2021        Berlin   94 PERCIVAL AVE

   Assessed Value  Sale Amount  Sales Ratio Property Type Residential Type  \
0          133000       248400     0.535400   Residential    Single Family
1          110500       239900     0.460600   Residential     Three Family
2          150500       325000     0.463000    Commercial              NaN
3          127400       202500     0.629100   Residential       Two Family
4          217640       400000     0.544100   Residential    Single Family
5          528490       775000     0.681900   Residential    Single Family
6          203530       415000     0.490434   Residential    Single Family
7          158030       243000     0.650300   Residential    Single Family
8           65590       100000     0.655900   Residential            Condo
9          140600       190790     0.736900   Residential    Single Family

  Non Use Code                   Assessor Remarks OPM remarks  \
0          NaN                                NaN         NaN
1          NaN                                NaN         NaN
2          NaN                                NaN         NaN
3          NaN                                NaN         NaN
4          NaN                                NaN         NaN
5          NaN                                NaN         NaN
6          NaN  2003 COLONIAL, 2140 SFLA, 2.99 AC         NaN
7          NaN                                NaN         NaN
8          NaN                                NaN         NaN
9          NaN                                NaN         NaN

                     Location
0  POINT (-73.06822 41.35014)
1                         NaN
2                         NaN
3                         NaN
4                         NaN
5  POINT (-72.89675 41.79445)
6                         NaN
7                         NaN
8                         NaN
9                         NaN



The number of data points are 500


Here are the column names:

Index(['Serial Number', 'List Year', 'Date Recorded', 'Town', 'Address',
       'Assessed Value', 'Sale Amount', 'Sales Ratio', 'Property Type',
       'Residential Type', 'Non Use Code', 'Assessor Remarks', 'OPM remarks',
       'Location'],
      dtype='object')


Here is a statistical summary:

        Serial Number    List Year  Assessed Value   Sale Amount  Sales Ratio
count   5.000000e+02   500.000000    5.000000e+02  5.000000e+02   500.000000
mean    2.544529e+06  2019.278000    2.397810e+05  4.247315e+05     0.634735
std     1.813926e+07     3.636367    3.103858e+05  5.210417e+05     0.825464
min     1.002200e+04  2001.000000    1.100000e+03  0.000000e+00     0.000000
25%     2.000475e+05  2020.000000    1.009450e+05  1.825000e+05     0.490858
50%     2.002855e+05  2020.000000    1.552350e+05  2.822000e+05     0.556150
75%     2.009858e+05  2020.000000    2.394750e+05  4.350000e+05     0.653525
max     2.020001e+08  2020.000000    2.712290e+06  4.800000e+06    13.020000


The years listed in the dataset:
0      2020
1      2020
2      2020
3      2020
4      2020
       ...
495    2020
496    2020
497    2020
498    2020
499    2020
Name: List Year, Length: 500, dtype: int64
On average, single-family homes are more expensive in Danbury.